# Generated by Django 5.1.5 on 2025-02-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la Empresa')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico de Contacto')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('business_hours', models.JSONField(blank=True, null=True, verbose_name='Horario de Atención')),
                ('social_media', models.JSONField(blank=True, null=True, verbose_name='Redes Sociales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='Palabra Clave')),
                ('response', models.TextField(verbose_name='Respuesta del Asistente')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_responses', to='assistant.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta Frecuente')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='assistant.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Producto')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='assistant.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Promoción')),
                ('description', models.TextField(verbose_name='Descripción de la Promoción')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento (%)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='assistant.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Servicio')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duración Aproximada')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='assistant.businessprofile')),
            ],
        ),
    ]
