# Generated by Django 5.1.5 on 2025-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='assistant_url_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Nombre url'),
            preserve_default=False,
        ),
    ]
